backend:
  name: github
  repo: MythicalFish/mythical.fish

media_folder: static/content/images
public_folder: /content/images

collections:
  - name: project
    label: Project
    folder: static/content/projects
    create: true
    fields:
      - {label: Type, name: type, widget: hidden, default: projects}
      - {label: Title, name: title, widget: string}
      - {label: Body, name: body, widget: markdown}
      - {label: Tags, name: tags, widget: list, optional: true}
      - {label: Links, name: links, widget: list, optional: true, fields: [{label: URL, name: url, widget: string}, {label: Label, name: label, widget: string}]}
      - {label: Previews, name: previews, widget: list, optional: true, fields: [{label: Image, name: image, widget: image}, {label: Label, name: label, widget: string}, {label: Description, name: description, widget: text}]}
      - {label: Position, name: position, widget: number, default: 0}
      - {label: Code is private, name: privateCode, widget: boolean, default: false}
      - {label: Visible, name: visible, widget: boolean, default: true}
  - name: info
    label: Info
    folder: static/content/info
    create: true
    fields:
      - {label: Type, name: type, widget: hidden, default: info}
      - {label: Key, name: key, widget: string}
      - {label: Body, name: body, widget: markdown, optional: true}
      - {label: Item List, name: itemList, widget: list, optional: true}