backend:
  name: github
  repo: MythicalFish/mythical.fish

media_folder: static/assets
public_folder: /assets

collections:
  - name: project
    label: Project
    folder: static/content/projects
    create: true
    slug: "{{slug}}"
    fields:
      - {label: Title, name: title, widget: string}
      - {label: Body, name: body, widget: markdown}
      - {label: Tags, name: tags, widget: list}
      - {label: Links, name: links, widget: list, fields: [{label: URL, name: url, widget: string}, {label: Label, name: label, widget: string}]}
      - {label: Position, name: position, widget: number, default: 0}