export const tagURLs = {
  Rails: "http://rubyonrails.org/",
  React: "https://reactjs.org/",
  Vue: "https://vuejs.org/",
  Sass: "https://sass-lang.com/",
  "Element UI": "http://element.eleme.io",
  PostCSS: "http://postcss.org/",
  Spree: "https://spreecommerce.org/",
  Wordpress: "https://wordpress.org/",
  Tachyons: "https://github.com/tachyons-css/tachyons/",
  Tailwind: "https://tailwindcss.com/",
  Gatsby: "https://www.gatsbyjs.org/",
  JS: "https://developer.mozilla.org/bm/docs/Web/JavaScript",
  HTML: "https://developer.mozilla.org/bm/docs/Web/html",
  GraphQL: "https://graphql.org/",
  Typescript: "https://www.typescriptlang.org/",
  Golang: "https://go.dev/",
};
